ALOE++ RTDAL API: /home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/pipeline_sync.c File Reference
pipeline_sync.c File Reference
#include <pthread.h>
#include <semaphore.h>
#include <string.h>
#include "futex.h"
#include "objects_max.h"
#include "pipeline_sync.h"
#include "defs.h"
Functions
int pipeline_sync_initialize (int _num_pipelines)
void pipeline_sync_thread_waits (int idx)
void pipeline_sync_threads_wake ()
Variables
int timeslot = 0
int timeslot_p [MAX_PIPELINES]
Function Documentation
int pipeline_sync_initialize (int _num_pipelines) inline
Definition at line 83 of file pipeline_sync.c.
References MAX_PIPELINES.
Referenced by pipeline_initialize().
void pipeline_sync_thread_waits (int idx) inline
Definition at line 104 of file pipeline_sync.c.
Referenced by pipeline_run_thread().
void pipeline_sync_threads_wake () inline
Definition at line 120 of file pipeline_sync.c.
Referenced by pipeline_sync_threads().
Variable Documentation
int timeslot = 0
Definition at line 18 of file pipeline_sync.c.
int timeslot_p[MAX_PIPELINES]
Definition at line 19 of file pipeline_sync.c.