ALOE++ RTDAL API: /home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/pipeline_sync.h File Reference
pipeline_sync.h File Reference
#include <pthread.h>
#include <semaphore.h>
#include "futex.h"
#include "objects_max.h"
Macros
#define MAX_PIPELINES 30
#define SEM 1
#define FUTEX 2
#define BARRIER 3
#define CONDVAR 4
#define PIPELINESYNC_MUTEX_TYPE 4
Functions
int pipeline_sync_initialize (int num_pipelines)
void pipeline_sync_thread_waits (int idx)
void pipeline_sync_threads_wake ()
Macro Definition Documentation
#define BARRIER 3
Definition at line 31 of file pipeline_sync.h.
#define CONDVAR 4
Definition at line 32 of file pipeline_sync.h.
#define FUTEX 2
Definition at line 30 of file pipeline_sync.h.
#define MAX_PIPELINES 30
Definition at line 27 of file pipeline_sync.h.
Referenced by pipeline_sync_initialize().
#define PIPELINESYNC_MUTEX_TYPE 4
Definition at line 34 of file pipeline_sync.h.
#define SEM 1
Definition at line 29 of file pipeline_sync.h.
Function Documentation
int pipeline_sync_initialize (int num_pipelines) inline
Definition at line 83 of file pipeline_sync.c.
References MAX_PIPELINES.
Referenced by pipeline_initialize().
void pipeline_sync_thread_waits (int idx) inline
Definition at line 104 of file pipeline_sync.c.
Referenced by pipeline_run_thread().
void pipeline_sync_threads_wake () inline
Definition at line 120 of file pipeline_sync.c.
Referenced by pipeline_sync_threads().