ALOE++ RTDAL API: /home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_kernel.h File Reference
rtdal_kernel.h File Reference
#include "pipeline.h"
Macros
#define KERNEL_RT_PRIO sched_get_priority_max(SCHED_FIFO)
#define ALOE_VERSION "ALOE++-0.6"
#define ALOE_YEAR 2013
#define TASK_TERMINATION_SIGNAL SIGUSR2
Functions
void kernel_tslot_run ()
int rtdal_kernel_sigwait_thread ()
int kernel_initialize_create_pipeline (pipeline_t *obj, int *wait_futex)
void kernel_cycle (void *x, struct timespec *time)
void dac_cycle (void)
void thread_signal_handler (int signum, siginfo_t *info, void *ctx)
void kernel_exit ()
int parse_config (char *config_file)
void sigwait_loop (void)
int kernel_initialize_setup_signals ()
Macro Definition Documentation
#define ALOE_VERSION "ALOE++-0.6"
Definition at line 26 of file rtdal_kernel.h.
#define ALOE_YEAR 2013
Definition at line 27 of file rtdal_kernel.h.
#define KERNEL_RT_PRIO sched_get_priority_max(SCHED_FIFO)
Definition at line 24 of file rtdal_kernel.h.
#define TASK_TERMINATION_SIGNAL SIGUSR2
Definition at line 31 of file rtdal_kernel.h.
Referenced by rtdal_task_kill(), sigwait_loop(), and thread_signal_handler().
Function Documentation
void dac_cycle (void)
Referenced by main().
void kernel_cycle (void * x, struct timespec * time)
This function is called by the internal timer, a DAC event or by the sync_slave, after the reception of a synchronization packet.
Definition at line 92 of file rtdal_kernel_thread.c.
References dac_sem, hdebug, kernel_tslot_run(), pipeline_sync_threads(), rtdal_time_reset_realtime(), SINGLE_TIMER, and using_uhd.
void kernel_exit ()
Definition at line 343 of file rtdal_kernel.c.
References rtdal_machine_t::clock_source, dac_sem, hdebug, rtdal_context_t::machine, MULTI_TIMER, pipeline_t::mytimer, rtdal_machine_t::nof_cores, rtdal_context_t::pipelines, rtdal_time_slot(), sigwait_stops, rtdal_timer_t::stop, pipeline_t::stop, uhd_close(), using_uhd, and write_debug_trace().
Referenced by sigwait_loop().
int kernel_initialize_create_pipeline (pipeline_t * obj, int * wait_futex)
Definition at line 151 of file rtdal_kernel.c.
References rtdal_timer_t::arg, rtdal_machine_t::clock_source, core_mapping, DETACHABLE, hdebug, pipeline_t::id, rtdal_machine_t::kernel_prio, rtdal_context_t::machine, rtdal_timer_t::mode, MULTI_TIMER, pipeline_t::mytimer, NANOSLEEP, rtdal_timer_t::period, rtdal_timer_t::period_function, pipeline_run_from_timer(), pipeline_run_thread(), rtdal_perror, rtdal_task_new_thread(), rtdal_timer_t::thread, pipeline_t::thread, timer_run_thread(), rtdal_machine_t::ts_len_us, rtdal_timer_t::wait_futex, and XENOMAI.
int kernel_initialize_setup_signals ()
Block all signals except (SIGSEGV,SIGILL,SIGFPE,SIGBUS), which sigwaited by the sigwait_thread
Definition at line 356 of file rtdal_kernel_signals.c.
References N_THREAD_SPECIFIC_SIGNALS, poserror, thread_signal_handler(), and thread_specific_signals.
void kernel_tslot_run () inline
Definition at line 74 of file rtdal_kernel_thread.c.
References hdebug, rtdal_time_slot(), rtdal_time_ts_inc(), and signal_received.
Referenced by kernel_cycle(), and pipeline_run_from_timer().
int parse_config (char * config_file)
Definition at line 95 of file rtdal_kernel_parse.c.
References aerror, aerror_msg, dac_cfg::chain_is_tx, DAC, dac_cfg::inputFreq, dac_cfg::inputRFFreq, libs_path, MULTI_TIMER, dac_cfg::nof_channels, nof_cores, dac_cfg::NsamplesIn, dac_cfg::NsamplesOut, dac_cfg::outputFreq, dac_cfg::outputRFFreq, parse_cores(), rtdal, dac_cfg::rx_bw, dac_cfg::rx_gain, dac_cfg::sampleType, SINGLE_TIMER, strcpy, timeslot_us, dac_cfg::tx_bw, dac_cfg::tx_gain, uhd_readcfg(), and using_uhd.
Referenced by main().
int rtdal_kernel_sigwait_thread ()
void sigwait_loop (void)
This is a thread with priority kernel_prio that synchronously waits for rtdal_pipeline signals (usign sigwaitinfo). All signals except thread-specific ones (SIGSEGV,SIGILL,SIGBUS,SIGFPE) are blocked by all threads except this one. Thread-specific signals are handled by ProcThreads which send a SIGRTMIN+1, SIGRTMIN+2,SIGRTMIN+3,SIGRTMIN+4 (respectively) to this thread, which takes actions accordingly.
for signals SIGRTMIN to SIGRTMIN+4, cast the rtdal_pipeline object from this si_value pointer and call rtdal_pipeline_recover_thread(pipeline, pipeline->running_process, TRUE)
Definition at line 97 of file rtdal_kernel_signals.c.
References hdebug, kernel_exit(), KERNEL_SIG_THREAD_SPECIFIC, poserror, sigwait_stops, and TASK_TERMINATION_SIGNAL.
Referenced by main().
void thread_signal_handler (int signum, siginfo_t * info, void * ctx)
Handler for thread-specific signals (SIGSEGV,SIGILL,SIGFPE,SIGBUS). Forwards a signal above SIGRTMIN to myself. Since it is blocked, it will be received by sigwait_loop(), which is runs in the main kernel thread.
The thread terminates after exiting the handler.
todo: Caution!! is pthread_self() safe in the handler? it is not async-signal-safe by the standard, but the signals are synchronous.
Definition at line 272 of file rtdal_kernel_signals.c.
References hdebug, kernel_pid, KERNEL_SIG_THREAD_SPECIFIC, rtdal_context_t::machine, N_THREAD_SPECIFIC_SIGNALS, rtdal_machine_t::nof_cores, rtdal_context_t::pipelines, poserror, rtdal_time_slot(), signal_received, single_timer_thread, TASK_TERMINATION_SIGNAL, pipeline_t::thread, thread_specific_signals, and pipeline_t::waiting.
Referenced by kernel_initialize_setup_signals().