ALOE++ RTDAL API: /home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_kernel.c File Reference
rtdal_kernel.c File Reference
#include <pthread.h>
#include <stdlib.h>
#include <stdio.h>
#include <signal.h>
#include <errno.h>
#include <sched.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/mman.h>
#include <semaphore.h>
#include "rtdal_kernel.h"
#include "str.h"
#include "defs.h"
#include "rtdal_time.h"
#include "rtdal_process.h"
#include "rtdal_context.h"
#include "rtdal_task.h"
#include "rtdal.h"
#include "rtdal_timer.h"
#include "futex.h"
Functions
void rtdal_timeslot_set (int ts_base_multiply)
int kernel_initialize_create_pipeline (pipeline_t *obj, int *wait_futex)
int kernel_initialize_set_kernel_priority ()
void open_debug_trace ()
void write_debug_trace ()
void kernel_exit ()
int main (int argc, char **argv)
Variables
int * core_mapping
int nof_cores
int using_uhd
rtdal_context_t rtdal
long int timeslot_us
enum clock_source clock_source
int sigwait_stops = 0
pid_t kernel_pid
pthread_t single_timer_thread
FILE * trace_buffer = NULL
char * debug_trace_addr
size_t debug_trace_sz
FILE * debug_trace_file
sem_t dac_sem
Function Documentation
void kernel_exit ()
Definition at line 343 of file rtdal_kernel.c.
References rtdal_machine_t::clock_source, dac_sem, hdebug, rtdal_context_t::machine, MULTI_TIMER, pipeline_t::mytimer, rtdal_machine_t::nof_cores, rtdal_context_t::pipelines, rtdal_time_slot(), sigwait_stops, rtdal_timer_t::stop, pipeline_t::stop, uhd_close(), using_uhd, and write_debug_trace().
Referenced by sigwait_loop().
int kernel_initialize_create_pipeline (pipeline_t * obj, int * wait_futex)
Definition at line 151 of file rtdal_kernel.c.
References rtdal_timer_t::arg, rtdal_machine_t::clock_source, core_mapping, DETACHABLE, hdebug, pipeline_t::id, rtdal_machine_t::kernel_prio, rtdal_context_t::machine, rtdal_timer_t::mode, MULTI_TIMER, pipeline_t::mytimer, NANOSLEEP, rtdal_timer_t::period, rtdal_timer_t::period_function, pipeline_run_from_timer(), pipeline_run_thread(), rtdal_perror, rtdal_task_new_thread(), rtdal_timer_t::thread, pipeline_t::thread, timer_run_thread(), rtdal_machine_t::ts_len_us, rtdal_timer_t::wait_futex, and XENOMAI.
int kernel_initialize_set_kernel_priority ()
Definition at line 211 of file rtdal_kernel.c.
References awarn, hdebug, rtdal_machine_t::kernel_prio, rtdal_context_t::machine, and poserror.
int main (int argc, char ** argv)
Definition at line 365 of file rtdal_kernel.c.
References _run_main(), aerror, aerror_msg, dac_cycle(), dac_sem, kernel_pid, rtdal_machine_t::kernel_prio, rtdal_context_t::machine, MULTI_TIMER, rtdal_machine_t::nof_cores, nof_cores, open_debug_trace(), parse_config(), rtdal_perror, rtdal_task_new(), sigwait_loop(), timeslot_us, rtdal_machine_t::ts_len_us, uhd_init(), using_uhd, and write_debug_trace().
void open_debug_trace ()
Definition at line 317 of file rtdal_kernel.c.
References debug_trace_addr, debug_trace_file, debug_trace_sz, and trace_buffer.
Referenced by main().
void write_debug_trace ()
Definition at line 328 of file rtdal_kernel.c.
References debug_trace_addr, debug_trace_file, debug_trace_sz, and trace_buffer.
Referenced by kernel_exit(), and main().
Variable Documentation
enum clock_source clock_source
Definition at line 56 of file rtdal_kernel.c.
int* core_mapping
Definition at line 48 of file rtdal_kernel.c.
Referenced by kernel_initialize_create_pipeline(), parse_cores_comma_sep(), parse_cores_single_array(), and rtdal_task_new_thread().
sem_t dac_sem
Definition at line 14 of file rtdal_kernel_thread.c.
Referenced by kernel_cycle(), kernel_exit(), and main().
char* debug_trace_addr
Definition at line 67 of file rtdal_kernel.c.
Referenced by open_debug_trace(), and write_debug_trace().
FILE* debug_trace_file
Definition at line 69 of file rtdal_kernel.c.
Referenced by open_debug_trace(), and write_debug_trace().
size_t debug_trace_sz
Definition at line 68 of file rtdal_kernel.c.
Referenced by open_debug_trace(), and write_debug_trace().
pid_t kernel_pid
Definition at line 60 of file rtdal_kernel.c.
Referenced by main(), rtdal_process_launch(), rtdal_process_remove(), and thread_signal_handler().
int nof_cores
Definition at line 49 of file rtdal_kernel.c.
Referenced by main(), parse_config(), and rtdal_task_new_thread().
rtdal_context_t rtdal
Definition at line 53 of file rtdal_kernel.c.
Referenced by parse_config().
int sigwait_stops = 0
Definition at line 58 of file rtdal_kernel.c.
Referenced by kernel_exit(), and sigwait_loop().
pthread_t single_timer_thread
Definition at line 61 of file rtdal_kernel.c.
Referenced by thread_signal_handler().
long int timeslot_us
Definition at line 55 of file rtdal_kernel.c.
Referenced by main(), and parse_config().
FILE* trace_buffer = NULL
Definition at line 66 of file rtdal_kernel.c.
Referenced by open_debug_trace(), and write_debug_trace().
int using_uhd
Definition at line 52 of file rtdal_kernel.c.
Referenced by kernel_cycle(), kernel_exit(), main(), and parse_config().