ALOE++ RTDAL API: /home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_kernel_signals.c File Reference
rtdal_kernel_signals.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <signal.h>
#include <string.h>
#include <errno.h>
#include <pthread.h>
#include <execinfo.h>
#include <unistd.h>
#include <dlfcn.h>
#include "rtdal_context.h"
#include "rtdal_kernel.h"
#include "str.h"
#include "defs.h"
Macros
#define NO_CPP_DEMANGLE
#define KERNEL_SIG_THREAD_SPECIFIC SIGRTMIN
#define N_THREAD_SPECIFIC_SIGNALS 7
#define sigsegv_outp(x,...) fprintf(stderr, x "\n", ##__VA_ARGS__)
#define SIGSEGV_STACK_GENERIC
#define REGFORMAT "%x"
#define PRINT_BT_ON_SIGSEGV
Functions
strdef (tmp_msg)
void sigwait_loop (void)
void print_backtrace (void)
void thread_signal_handler (int signum, siginfo_t *info, void *ctx)
int kernel_initialize_setup_signals ()
Variables
const int thread_specific_signals [N_THREAD_SPECIFIC_SIGNALS]
const char * thread_specific_signals_name [N_THREAD_SPECIFIC_SIGNALS]
int sigwait_stops
rtdal_context_t rtdal
int signal_received
pthread_t single_timer_thread
pid_t kernel_pid
void * bt [1024]
Macro Definition Documentation
#define KERNEL_SIG_THREAD_SPECIFIC SIGRTMIN
Definition at line 20 of file rtdal_kernel_signals.c.
Referenced by sigwait_loop(), and thread_signal_handler().
#define N_THREAD_SPECIFIC_SIGNALS 7
Definition at line 21 of file rtdal_kernel_signals.c.
Referenced by kernel_initialize_setup_signals(), and thread_signal_handler().
#define NO_CPP_DEMANGLE
Definition at line 11 of file rtdal_kernel_signals.c.
#define PRINT_BT_ON_SIGSEGV
Definition at line 263 of file rtdal_kernel_signals.c.
#define REGFORMAT "%x"
Definition at line 184 of file rtdal_kernel_signals.c.
#define sigsegv_outp (x, ...) fprintf(stderr, x "\n", ##__VA_ARGS__)
Definition at line 174 of file rtdal_kernel_signals.c.
#define SIGSEGV_STACK_GENERIC
Definition at line 183 of file rtdal_kernel_signals.c.
Function Documentation
int kernel_initialize_setup_signals ()
Block all signals except (SIGSEGV,SIGILL,SIGFPE,SIGBUS), which sigwaited by the sigwait_thread
Definition at line 356 of file rtdal_kernel_signals.c.
References N_THREAD_SPECIFIC_SIGNALS, poserror, thread_signal_handler(), and thread_specific_signals.
void print_backtrace (void)
FIXME: Use REG_RIP on IA64
Definition at line 153 of file rtdal_kernel_signals.c.
void sigwait_loop (void)
This is a thread with priority kernel_prio that synchronously waits for rtdal_pipeline signals (usign sigwaitinfo). All signals except thread-specific ones (SIGSEGV,SIGILL,SIGBUS,SIGFPE) are blocked by all threads except this one. Thread-specific signals are handled by ProcThreads which send a SIGRTMIN+1, SIGRTMIN+2,SIGRTMIN+3,SIGRTMIN+4 (respectively) to this thread, which takes actions accordingly.
for signals SIGRTMIN to SIGRTMIN+4, cast the rtdal_pipeline object from this si_value pointer and call rtdal_pipeline_recover_thread(pipeline, pipeline->running_process, TRUE)
Definition at line 97 of file rtdal_kernel_signals.c.
References hdebug, kernel_exit(), KERNEL_SIG_THREAD_SPECIFIC, poserror, sigwait_stops, and TASK_TERMINATION_SIGNAL.
Referenced by main().
strdef (tmp_msg)
void thread_signal_handler (int signum, siginfo_t * info, void * ctx)
Handler for thread-specific signals (SIGSEGV,SIGILL,SIGFPE,SIGBUS). Forwards a signal above SIGRTMIN to myself. Since it is blocked, it will be received by sigwait_loop(), which is runs in the main kernel thread.
The thread terminates after exiting the handler.
todo: Caution!! is pthread_self() safe in the handler? it is not async-signal-safe by the standard, but the signals are synchronous.
Definition at line 272 of file rtdal_kernel_signals.c.
References hdebug, kernel_pid, KERNEL_SIG_THREAD_SPECIFIC, rtdal_context_t::machine, N_THREAD_SPECIFIC_SIGNALS, rtdal_machine_t::nof_cores, rtdal_context_t::pipelines, poserror, rtdal_time_slot(), signal_received, single_timer_thread, TASK_TERMINATION_SIGNAL, pipeline_t::thread, thread_specific_signals, and pipeline_t::waiting.
Referenced by kernel_initialize_setup_signals().
Variable Documentation
void* bt[1024]
Definition at line 150 of file rtdal_kernel_signals.c.
pid_t kernel_pid
Definition at line 60 of file rtdal_kernel.c.
rtdal_context_t rtdal
Definition at line 53 of file rtdal_kernel.c.
int signal_received
Definition at line 15 of file rtdal_kernel_thread.c.
Referenced by kernel_tslot_run(), and thread_signal_handler().
int sigwait_stops
Definition at line 58 of file rtdal_kernel.c.
pthread_t single_timer_thread
Definition at line 61 of file rtdal_kernel.c.
Referenced by thread_signal_handler().
const int thread_specific_signals[N_THREAD_SPECIFIC_SIGNALS]
Initial value:
        {SIGSEGV, SIGABRT, SIGBUS, SIGILL, SIGFPE, TASK_TERMINATION_SIGNAL, SIGUSR1}
Definition at line 22 of file rtdal_kernel_signals.c.
Referenced by kernel_initialize_setup_signals(), and thread_signal_handler().
const char* thread_specific_signals_name[N_THREAD_SPECIFIC_SIGNALS]
Initial value:
        {"SIGSEGV", "SIGABRT", "SIGBUS", "SIGILL", "SIGFPE", "TASK_TERMINATION_SIGNAL", "SIGUSR1"}
Definition at line 24 of file rtdal_kernel_signals.c.