ALOE++ RTDAL API: /home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_kernel_parse.c File Reference
rtdal_kernel_parse.c File Reference
#include <stdlib.h>
#include <stddef.h>
#include <libconfig.h>
#include <assert.h>
#include "rtdal_kernel.h"
#include "defs.h"
Functions
int parse_cores_comma_sep (char *str)
int parse_cores_single_array (char *core_init, char *core_end)
int parse_cores (char *str)
int parse_config (char *config_file)
Variables
char libs_path [255]
int * core_mapping
int nof_cores
long int timeslot_us
enum clock_source clock_source
int using_uhd
Function Documentation
int parse_config (char * config_file)
Definition at line 95 of file rtdal_kernel_parse.c.
References aerror, aerror_msg, dac_cfg::chain_is_tx, DAC, dac_cfg::inputFreq, dac_cfg::inputRFFreq, libs_path, MULTI_TIMER, dac_cfg::nof_channels, nof_cores, dac_cfg::NsamplesIn, dac_cfg::NsamplesOut, dac_cfg::outputFreq, dac_cfg::outputRFFreq, parse_cores(), rtdal, dac_cfg::rx_bw, dac_cfg::rx_gain, dac_cfg::sampleType, SINGLE_TIMER, strcpy, timeslot_us, dac_cfg::tx_bw, dac_cfg::tx_gain, uhd_readcfg(), and using_uhd.
Referenced by main().
int parse_cores (char * str)
Parses a string indicating which cores can be used to load modules Valid string formats are:
"N" Just a number, without "," nor ":" means to use core id 0 to N-1
"n1:n2" Indicates that core ids n1 to n2 will be used
"n1,n2,n3" Indicates that core ids n1, n2 and n3 only will be used
Definition at line 75 of file rtdal_kernel_parse.c.
References c, parse_cores_comma_sep(), and parse_cores_single_array().
Referenced by parse_config().
int parse_cores_comma_sep (char * str)
Definition at line 26 of file rtdal_kernel_parse.c.
References core_mapping.
Referenced by parse_cores().
int parse_cores_single_array (char * core_init, char * core_end)
Definition at line 50 of file rtdal_kernel_parse.c.
References core_mapping.
Referenced by parse_cores().
Variable Documentation
enum clock_source clock_source
Definition at line 56 of file rtdal_kernel.c.
int* core_mapping
Definition at line 48 of file rtdal_kernel.c.
char libs_path[255]
Definition at line 16 of file rtdal_kernel_parse.c.
Referenced by parse_config(), and rtdal_process_launch().
int nof_cores
Definition at line 49 of file rtdal_kernel.c.
long int timeslot_us
Definition at line 55 of file rtdal_kernel.c.
int using_uhd
Definition at line 52 of file rtdal_kernel.c.