ALOE++ RTDAL API: /home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_timer.c File Reference
rtdal_timer.c File Reference
#include <pthread.h>
#include <unistd.h>
#include <stdlib.h>
#include <signal.h>
#include <time.h>
#include <error.h>
#include "defs.h"
#include "rtdal_timer.h"
#include "rtdal.h"
#include "futex.h"
Functions
void * timer_run_thread (void *x)
void timespec_sub_us (struct timespec *t, long int us)
void * nanoclock_timer_run_thread (rtdal_timer_t *obj)
Variables
int timeslot
Function Documentation
void* nanoclock_timer_run_thread (rtdal_timer_t * obj)
Definition at line 192 of file rtdal_timer.c.
References rtdal_timer_t::arg, futex_wait, rtdal_timer_t::multiple, n, rtdal_timer_t::next, rtdal_timer_t::period, rtdal_timer_t::period_function, rtdal_timer_t::stop, TIMER_FUTEX_GUARD_SEC, and rtdal_timer_t::wait_futex.
Referenced by timer_run_thread().
void* timer_run_thread (void * x)
Definition at line 114 of file rtdal_timer.c.
References aerror, aerror_msg, DEBUG_rtdal, rtdal_timer_t::mode, nanoclock_timer_run_thread(), NANOSLEEP, rtdal_task_print_sched(), TIMERFD, timerfd_timer_run_thread(), and XENOMAI.
Referenced by kernel_initialize_create_pipeline().
void timespec_sub_us (struct timespec * t, long int us)
Definition at line 184 of file rtdal_timer.c.
Variable Documentation
int timeslot
Definition at line 18 of file pipeline_sync.c.