ALOE++ RTDAL API: /home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_kernel_thread.c File Reference
rtdal_kernel_thread.c File Reference
#include <stdlib.h>
#include <stddef.h>
#include <libconfig.h>
#include <assert.h>
#include <semaphore.h>
#include "rtdal_kernel.h"
#include "pipeline.h"
#include "rtdal_context.h"
#include "rtdal_time.h"
Functions
void kernel_tslot_run ()
void kernel_cycle (void *x, struct timespec *time)
Variables
sem_t dac_sem
int signal_received = 0
long int timeslot_us
enum clock_source clock_source
int using_uhd
rtdal_context_t rtdal
int sigwait_stops
Function Documentation
void kernel_cycle (void * x, struct timespec * time)
This function is called by the internal timer, a DAC event or by the sync_slave, after the reception of a synchronization packet.
Definition at line 92 of file rtdal_kernel_thread.c.
References dac_sem, hdebug, kernel_tslot_run(), pipeline_sync_threads(), rtdal_time_reset_realtime(), SINGLE_TIMER, and using_uhd.
void kernel_tslot_run () inline
Definition at line 74 of file rtdal_kernel_thread.c.
References hdebug, rtdal_time_slot(), rtdal_time_ts_inc(), and signal_received.
Referenced by kernel_cycle(), and pipeline_run_from_timer().
Variable Documentation
enum clock_source clock_source
Definition at line 56 of file rtdal_kernel.c.
sem_t dac_sem
Definition at line 14 of file rtdal_kernel_thread.c.
Referenced by kernel_cycle(), kernel_exit(), and main().
rtdal_context_t rtdal
Definition at line 53 of file rtdal_kernel.c.
Referenced by parse_config().
int signal_received = 0
Definition at line 15 of file rtdal_kernel_thread.c.
Referenced by kernel_tslot_run(), and thread_signal_handler().
int sigwait_stops
Definition at line 58 of file rtdal_kernel.c.
Referenced by kernel_exit(), and sigwait_loop().
long int timeslot_us
Definition at line 55 of file rtdal_kernel.c.
Referenced by main(), and parse_config().
int using_uhd
Definition at line 52 of file rtdal_kernel.c.
Referenced by kernel_cycle(), kernel_exit(), main(), and parse_config().