ALOE++ RTDAL API: /home/ismael/aloe_ws/aloe_git/rtdal_lnx/dac/soundcard/sndcard_imp.c File Reference
sndcard_imp.c File Reference
#include <stdio.h>
#include <errno.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <jack/jack.h>
#include "set.h"
#include "str.h"
#include "cfg_parser.h"
Typedefs
typedef jack_default_audio_sample_t sample_t
Functions
int process (jack_nframes_t nframes, void *arg)
int bufferchg (jack_nframes_t nframes, void *arg)
int srate (jack_nframes_t nframes, void *arg)
void error (const char *desc)
void jack_shutdown (void *arg)
int sndcard_readcfg (char *name, int *NsamplesIn, int *NsamplesOut)
int sndcard_init (int *ts_len, float *rxBuffer, float *txBuffer, void(*sync)(void))
void sndcard_close ()
Variables
jack_port_t * input_port
jack_port_t * output_port
jack_client_t * client
const double PI = 3.14
int semid
int semidx
float * output
float * input
jack_nframes_t samincy
long offset = 0
int tone = 492
void(* syncFunction)(void)
char filepath [200]
int SamplingFrequency
int NofSamples
Typedef Documentation
typedef jack_default_audio_sample_t sample_t
Definition at line 25 of file sndcard_imp.c.
Function Documentation
int bufferchg (jack_nframes_t nframes, void * arg)
Definition at line 63 of file sndcard_imp.c.
Referenced by sndcard_init().
void error (const char * desc)
Definition at line 73 of file sndcard_imp.c.
Referenced by rtdal_process_launch(), sndcard_init(), and x5_readcfg().
void jack_shutdown (void * arg)
JACK calls this shutdown_callback if the server ever shuts down or decides to disconnect the client.
Definition at line 81 of file sndcard_imp.c.
Referenced by sndcard_init().
int process (jack_nframes_t nframes, void * arg)
The process callback for this JACK application is called in a special realtime thread once for each audio cycle.
This client does nothing more than copy data from its input port to its output port. It will exit when stopped by the user (e.g. using Ctrl-C on a unix-ish operating system)
Definition at line 50 of file sndcard_imp.c.
References input, input_port, output, output_port, and syncFunction.
Referenced by pipeline_add(), and sndcard_init().
void sndcard_close ()
Definition at line 273 of file sndcard_imp.c.
References client.
int sndcard_init (int * ts_len, float * rxBuffer, float * txBuffer, void(*)(void) sync)
Definition at line 152 of file sndcard_imp.c.
References bufferchg(), client, error(), input, input_port, jack_shutdown(), NofSamples, output, output_port, process(), SamplingFrequency, srate(), and syncFunction.
int sndcard_readcfg (char * name, int * NsamplesIn, int * NsamplesOut)
Definition at line 90 of file sndcard_imp.c.
References filepath, NofSamples, offset, SamplingFrequency, and strcmp.
int srate (jack_nframes_t nframes, void * arg)
Definition at line 68 of file sndcard_imp.c.
Referenced by sndcard_init().
Variable Documentation
jack_client_t* client
Definition at line 21 of file sndcard_imp.c.
Referenced by sndcard_close(), and sndcard_init().
char filepath[200]
Definition at line 85 of file sndcard_imp.c.
Referenced by sndcard_readcfg(), and x5_readcfg().
float * input
Definition at line 31 of file sndcard_imp.c.
Referenced by process(), and sndcard_init().
jack_port_t* input_port
Definition at line 19 of file sndcard_imp.c.
Referenced by process(), and sndcard_init().
int NofSamples
Definition at line 88 of file sndcard_imp.c.
Referenced by sndcard_init(), and sndcard_readcfg().
long offset = 0
Definition at line 35 of file sndcard_imp.c.
Referenced by sndcard_readcfg(), and x5_readcfg().
float* output
Definition at line 31 of file sndcard_imp.c.
Referenced by process(), and sndcard_init().
jack_port_t* output_port
Definition at line 20 of file sndcard_imp.c.
Referenced by process(), and sndcard_init().
const double PI = 3.14
Definition at line 23 of file sndcard_imp.c.
jack_nframes_t samincy
Definition at line 33 of file sndcard_imp.c.
int SamplingFrequency
Definition at line 87 of file sndcard_imp.c.
Referenced by sndcard_init(), and sndcard_readcfg().
int semid
Definition at line 27 of file sndcard_imp.c.
int semidx
Definition at line 27 of file sndcard_imp.c.
void(* syncFunction)(void)
Definition at line 40 of file sndcard_imp.c.
Referenced by process(), and sndcard_init().
int tone = 492
Definition at line 38 of file sndcard_imp.c.