ALOE++ RTDAL API: /home/ismael/aloe_ws/aloe_git/rtdal_lnx/dac/include/sndcard.h File Reference
sndcard.h File Reference
Functions
int sndcard_readcfg (char *filename, int *NsamplesIn, int *NsamplesOut)
int sndcard_init (int *timeSlot, float *rxBuffer, float *txBuffer, void(*sync)(void))
void sndcard_close ()
Function Documentation
void sndcard_close ()
Definition at line 273 of file sndcard_imp.c.
References client.
int sndcard_init (int * timeSlot, float * rxBuffer, float * txBuffer, void(*)(void) sync)
Definition at line 152 of file sndcard_imp.c.
References bufferchg(), client, error(), input, input_port, jack_shutdown(), NofSamples, output, output_port, process(), SamplingFrequency, srate(), and syncFunction.
int sndcard_readcfg (char * filename, int * NsamplesIn, int * NsamplesOut)
Definition at line 90 of file sndcard_imp.c.
References filepath, NofSamples, offset, SamplingFrequency, and strcmp.