ALOE++ RTDAL API: /home/ismael/aloe_ws/aloe_git/rtdal_lnx/dac/include/uhd.h File Reference
uhd.h File Reference
Data Structures
struct main_conf
Functions
int uhd_readcfg (struct dac_cfg *dac_cfg)
int uhd_init (struct dac_cfg *cfg, long int *timeSlotLength, void(*sync)(void))
void uhd_close ()
void uhd_setcfg (struct main_conf *main, struct dac_cfg *dac_cfg)
Function Documentation
void uhd_close ()
Definition at line 312 of file uhd_imp.cpp.
Referenced by kernel_exit().
int uhd_init (struct dac_cfg * cfg, long int * timeSlotLength, void(*)(void) sync)
Set receive chain
Set transmit chain
Definition at line 239 of file uhd_imp.cpp.
References main_conf::chain_is_tx, dac_cfg::inputFreq, dac_cfg::inputRFFreq, main_cfg, dac_cfg::NsamplesOut, dac_cfg::outputFreq, dac_cfg::outputRFFreq, dac_cfg::rx_bw, dac_cfg::rx_gain, rx_thread(), dac_cfg::sampleType, string, dac_cfg::tx_bw, dac_cfg::tx_gain, and tx_thread().
Referenced by main().
int uhd_readcfg (struct dac_cfg * dac_cfg)
Definition at line 12 of file uhd_parser.c.
References main_conf::chain_is_tx, dac_cfg::chain_is_tx, main_conf::clock, main_cfg, and uhd_setcfg().
Referenced by parse_config().
void uhd_setcfg (struct main_conf * main, struct dac_cfg * dac_cfg)
Definition at line 222 of file uhd_imp.cpp.
References main_cfg, dac_cfg::outputFreq, and string.
Referenced by uhd_readcfg().