ALOE++ RTDAL API: /home/ismael/aloe_ws/aloe_git/rtdal_lnx/dac/uhd/uhd_imp.cpp File Reference
uhd_imp.cpp File Reference
#include <uhd/utils/thread_priority.hpp>
#include <uhd/convert.hpp>
#include <uhd/utils/safe_main.hpp>
#include <uhd/usrp/multi_usrp.hpp>
#include <boost/thread/thread.hpp>
#include <iostream>
#include <complex>
#include <cstdio>
#include <signal.h>
#include <semaphore.h>
#include <string.h>
#include "uhd.h"
#include "dac_cfg.h"
Macros
#define SAVE_LEN 100000
Functions
void rx_thread (uhd::usrp::multi_usrp::sptr usrp, const std::string &rx_cpu, const std::string &rx_otw, struct dac_cfg *cfg, void(*sync)(void), long int *tslen_ptr)
void time_interval (struct timeval *tdata)
void tx_thread (uhd::usrp::multi_usrp::sptr usrp, const std::string &tx_cpu, const std::string &tx_otw, struct dac_cfg *cfg, void(*sync_ts)(void), long int *tslen_ptr)
void benchmark_tx_rate_async_helper (uhd::usrp::multi_usrp::sptr usrp)
void uhd_setcfg (struct main_conf *main, struct dac_cfg *cfg)
int uhd_init (struct dac_cfg *cfg, long int *timeSlotLength, void(*sync)(void))
void uhd_close ()
Variables
unsigned long long num_overflows = 0
unsigned long long num_underflows = 0
unsigned long long num_rx_samps = 0
unsigned long long num_tx_samps = 0
unsigned long long num_dropped_samps = 0
unsigned long long num_seq_errors = 0
int save_period [SAVE_LEN]
int save_idx = 0
struct timeval t [3]
double mean_interval = 0
int ct = 0
struct dac_cfg * def_cfg
boost::thread_group thread_group
uhd::usrp::multi_usrp::sptr usrp
struct main_conf main_cfg
Macro Definition Documentation
#define SAVE_LEN 100000
Definition at line 43 of file uhd_imp.cpp.
Function Documentation
void benchmark_tx_rate_async_helper (uhd::usrp::multi_usrp::sptr usrp)
Definition at line 188 of file uhd_imp.cpp.
References num_seq_errors, and num_underflows.
void rx_thread (uhd::usrp::multi_usrp::sptr usrp, const std::string & rx_cpu, const std::string & rx_otw, struct dac_cfg * cfg, void(*)(void) sync, long int * tslen_ptr)
Definition at line 55 of file uhd_imp.cpp.
References dac_cfg::dacinbuff, dac_cfg::inputFreq, dac_cfg::NsamplesIn, dac_cfg::NsamplesOut, num_dropped_samps, num_overflows, and num_rx_samps.
Referenced by uhd_init().
void time_interval (struct timeval * tdata)
Definition at line 117 of file uhd_imp.cpp.
void tx_thread (uhd::usrp::multi_usrp::sptr usrp, const std::string & tx_cpu, const std::string & tx_otw, struct dac_cfg * cfg, void(*)(void) sync_ts, long int * tslen_ptr)
Definition at line 135 of file uhd_imp.cpp.
References dac_cfg::dacoutbuff, n, dac_cfg::NsamplesOut, and dac_cfg::outputFreq.
Referenced by uhd_init().
void uhd_close ()
Definition at line 312 of file uhd_imp.cpp.
Referenced by kernel_exit().
int uhd_init (struct dac_cfg * cfg, long int * timeSlotLength, void(*)(void) sync)
Set receive chain
Set transmit chain
Definition at line 239 of file uhd_imp.cpp.
References main_conf::chain_is_tx, dac_cfg::inputFreq, dac_cfg::inputRFFreq, main_cfg, dac_cfg::NsamplesOut, dac_cfg::outputFreq, dac_cfg::outputRFFreq, dac_cfg::rx_bw, dac_cfg::rx_gain, rx_thread(), dac_cfg::sampleType, string, dac_cfg::tx_bw, dac_cfg::tx_gain, and tx_thread().
Referenced by main().
void uhd_setcfg (struct main_conf * main, struct dac_cfg * cfg)
Definition at line 222 of file uhd_imp.cpp.
References main_cfg, dac_cfg::outputFreq, and string.
Referenced by uhd_readcfg().
Variable Documentation
int ct = 0
Definition at line 49 of file uhd_imp.cpp.
struct dac_cfg* def_cfg
Definition at line 50 of file uhd_imp.cpp.
struct main_conf main_cfg
Definition at line 220 of file uhd_imp.cpp.
Referenced by uhd_init(), uhd_readcfg(), and uhd_setcfg().
double mean_interval = 0
Definition at line 48 of file uhd_imp.cpp.
unsigned long long num_dropped_samps = 0
Definition at line 40 of file uhd_imp.cpp.
Referenced by rx_thread().
unsigned long long num_overflows = 0
Definition at line 36 of file uhd_imp.cpp.
Referenced by rx_thread().
unsigned long long num_rx_samps = 0
Definition at line 38 of file uhd_imp.cpp.
Referenced by rx_thread().
unsigned long long num_seq_errors = 0
Definition at line 41 of file uhd_imp.cpp.
Referenced by benchmark_tx_rate_async_helper().
unsigned long long num_tx_samps = 0
Definition at line 39 of file uhd_imp.cpp.
unsigned long long num_underflows = 0
Definition at line 37 of file uhd_imp.cpp.
Referenced by benchmark_tx_rate_async_helper().
int save_idx = 0
Definition at line 45 of file uhd_imp.cpp.
int save_period[SAVE_LEN]
Definition at line 44 of file uhd_imp.cpp.
struct timeval t[3]
Definition at line 47 of file uhd_imp.cpp.
boost::thread_group thread_group
Definition at line 217 of file uhd_imp.cpp.
uhd::usrp::multi_usrp::sptr usrp
Definition at line 218 of file uhd_imp.cpp.